name: stratos_workspace
description: Workspace for stratos packages
publish_to: none

environment:
  sdk: ^3.7.1

dev_dependencies:
  melos: ^7.0.0-dev.7

workspace:
  - packages/stratos
  - packages/stratos_core
  - packages/stratos_json
  - packages/stratos_jsonc
  - packages/stratos_yaml
  - packages/stratos_markdown

melos:
  sdkPath: .dvm/dart_sdk

  ide:
    intellij:
      enabled: false

  command:
    bootstrap:
      environment:
        sdk: ^3.7.1
      dependencies:
        args: ^2.6.0
        path: ^1.9.1
      dev_dependencies:
        test: ^1.25.15
      hooks:
        pre: |
          rm -f pubspec_overrides.yaml
          cat > pubspec_overrides.yaml << \EOF
          workspace:
            - packages/stratos_core
            - packages/stratos_json
            - packages/stratos_jsonc
            - packages/stratos_yaml
            - packages/stratos_markdown
          EOF

          rm -f packages/stratos/pubspec_overrides.yaml
          cat > packages/stratos/pubspec_overrides.yaml << \EOF
          resolution:

          dependency_overrides:
            stratos_core:
              path: ../stratos_core
            stratos_json:
              path: ../stratos_json
            stratos_jsonc:
              path: ../stratos_jsonc
            stratos_markdown:
              path: ../stratos_markdown
            stratos_yaml:
              path: ../stratos_yaml
          EOF

  scripts:
    test:
      description: Run tests for Dart packages.
      run: dart test
      exec:
        orderDependents: true
      packageFilters:
        dependsOn: test
        dirExists: test
