name: stratos_workspace
description: Workspace for stratos packages
publish_to: none

environment:
  sdk: ^3.7.1

dev_dependencies:
  melos: ^7.0.0-dev.7

workspace:
  - packages/stratos
  - packages/stratos_json
  - packages/stratos_jsonc
  - packages/stratos_yaml
  - packages/stratos_markdown
