name: stratos_core
description: Core package for stratos_json, stratos_jsonc, stratos_markdown, and stratos_yaml packages.
version: 0.0.1
homepage: https://github.com/blendfactory/stratos/tree/main/packages/stratos_core
repository: https://github.com/blendfactory/stratos

resolution: workspace

environment:
  sdk: ^3.7.1

dependencies:
  meta: ^1.12.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.15
