name: stratos_markdown
description: A tool for linting and formatting Markdown files
version: 0.0.1
homepage: https://github.com/blendfactory/stratos/tree/main/packages/stratos_markdown
repository: https://github.com/blendfactory/stratos

resolution: workspace

environment:
  sdk: ^3.7.1

dependencies:
  path: ^1.9.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
