name: stratos
description: A tool for linting and formatting JSON, JSONC, YAML, and Markdown files
version: 0.0.1
homepage: https://github.com/blendfactory/stratos/tree/main/packages/stratos
repository: https://github.com/blendfactory/stratos

resolution: workspace

environment:
  sdk: ^3.7.1

dependencies:
  args: ^2.6.0
  path: ^1.9.1
  stratos_json: ^0.0.1
  stratos_jsonc: ^0.0.1
  stratos_markdown: ^0.0.1
  stratos_yaml: ^0.0.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.15
