name: stratos
description: A tool for linting and formatting JSON, JSONC, YAML, and Markdown files
version: 0.0.1
repository: https://github.com/blendfactory/stratos

resolution: workspace

environment:
  sdk: ^3.7.1

# Add regular dependencies here.
dependencies:
  args: ^2.5.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
