name: stratos_json
description: A tool for linting and formatting JSON files
version: 0.0.1
homepage: https://github.com/blendfactory/stratos/tree/main/packages/stratos_json
repository: https://github.com/blendfactory/stratos

resolution: workspace

environment:
  sdk: ^3.7.1

dependencies:
  path: ^1.9.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.15
